import {
  SaleTransaction,
  Expense,
  Customer,
  RepeatCustomer,
  Promotion,
  WhatsAppAutomation,
  Reminder,
  User,
  CompanySettings,
  Purchase,
} from './types';

export const mockSalesData: SaleTransaction[] = [
  {
    id: '1',
    date: '2024-01-23',
    productName: 'Laptop Pro 15',
    category: 'Electronics',
    amount: 85000,
    quantity: 1,
    customerName: 'Rajesh Kumar',
    customerPhone: '+254 712 345 678',
    paymentMethod: 'Bank Transfer',
    status: 'completed',
  },
  {
    id: '2',
    date: '2024-01-22',
    productName: 'Office Chair Executive',
    category: 'Furniture',
    amount: 15000,
    quantity: 2,
    customerName: 'Priya Sharma',
    customerPhone: '+254 713 456 789',
    paymentMethod: 'Credit Card',
    status: 'completed',
  },
  {
    id: '3',
    date: '2024-01-21',
    productName: 'Wireless Mouse',
    category: 'Accessories',
    amount: 2500,
    quantity: 5,
    customerName: 'Amit Patel',
    customerPhone: '+254 714 567 890',
    paymentMethod: 'Cash',
    status: 'completed',
  },
  {
    id: '4',
    date: '2024-01-20',
    productName: 'USB-C Cable',
    category: 'Accessories',
    amount: 1200,
    quantity: 10,
    customerName: 'Deepak Verma',
    customerPhone: '+254 715 678 901',
    paymentMethod: 'Debit Card',
    status: 'pending',
  },
  {
    id: '5',
    date: '2024-01-19',
    productName: 'Monitor 27 inch 4K',
    category: 'Electronics',
    amount: 32000,
    quantity: 1,
    customerName: 'Sneha Singh',
    customerPhone: '+254 716 789 012',
    paymentMethod: 'Bank Transfer',
    status: 'completed',
  },
  {
    id: '6',
    date: '2024-01-18',
    productName: 'Desk Lamp LED',
    category: 'Office Supplies',
    amount: 3500,
    quantity: 3,
    customerName: 'Vikram Kumar',
    customerPhone: '+254 717 890 123',
    paymentMethod: 'Credit Card',
    status: 'completed',
  },
  {
    id: '7',
    date: '2024-01-17',
    productName: 'Keyboard Mechanical',
    category: 'Accessories',
    amount: 8000,
    quantity: 1,
    customerName: 'Neha Gupta',
    customerPhone: '+254 718 901 234',
    paymentMethod: 'Debit Card',
    status: 'completed',
  },
  {
    id: '8',
    date: '2024-01-16',
    productName: 'Webcam HD',
    category: 'Electronics',
    amount: 5500,
    quantity: 2,
    customerName: 'Rajesh Kumar',
    customerPhone: '+254 712 345 678',
    paymentMethod: 'Cash',
    status: 'completed',
  },
];

export const mockExpensesData: Expense[] = [
  {
    id: '1',
    date: '2024-01-15',
    category: 'Inventory',
    description: 'Raw materials purchase',
    amount: 8000,
    paymentMethod: 'Bank Transfer',
    status: 'paid',
  },
  {
    id: '2',
    date: '2024-01-14',
    category: 'Marketing',
    description: 'Facebook & Instagram ads',
    amount: 3000,
    paymentMethod: 'Card',
    status: 'paid',
  },
  {
    id: '3',
    date: '2024-01-13',
    category: 'Utilities',
    description: 'Office electricity and water',
    amount: 2500,
    paymentMethod: 'Bank Transfer',
    status: 'paid',
  },
  {
    id: '4',
    date: '2024-01-12',
    category: 'Salaries',
    description: 'Employee salaries - January',
    amount: 25000,
    paymentMethod: 'Bank Transfer',
    status: 'paid',
  },
  {
    id: '5',
    date: '2024-01-12',
    category: 'Office Supplies',
    description: 'Stationery and supplies',
    amount: 1200,
    paymentMethod: 'Cash',
    status: 'paid',
  },
  {
    id: '6',
    date: '2024-01-11',
    category: 'Rent',
    description: 'Office rent - January',
    amount: 15000,
    paymentMethod: 'Bank Transfer',
    status: 'paid',
  },
  {
    id: '7',
    date: '2024-01-11',
    category: 'Transportation',
    description: 'Fuel and vehicle maintenance',
    amount: 2000,
    paymentMethod: 'Cash',
    status: 'pending',
  },
  {
    id: '8',
    date: '2024-01-10',
    category: 'Technology',
    description: 'Software licenses',
    amount: 5000,
    paymentMethod: 'Card',
    status: 'paid',
  },
];

export const mockCustomersData: Customer[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    phone: '+254 712 345 678',
    location: 'Nairobi',
    joinDate: '2024-01-01',
    totalSpent: 90500,
    visitCount: 2,
    status: 'active',
    lastPurchase: '2024-01-23',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    phone: '+254 713 456 789',
    location: 'Mombasa',
    joinDate: '2024-01-15',
    totalSpent: 15000,
    visitCount: 1,
    status: 'active',
    lastPurchase: '2024-01-22',
  },
  {
    id: '3',
    name: 'Amit Patel',
    phone: '+254 714 567 890',
    location: 'Kisumu',
    joinDate: '2024-01-16',
    totalSpent: 2500,
    visitCount: 1,
    status: 'active',
    lastPurchase: '2024-01-21',
  },
  {
    id: '4',
    name: 'Deepak Verma',
    phone: '+254 715 678 901',
    location: 'Nakuru',
    joinDate: '2024-01-17',
    totalSpent: 1200,
    visitCount: 1,
    status: 'active',
    lastPurchase: '2024-01-20',
  },
  {
    id: '5',
    name: 'Sneha Singh',
    phone: '+254 716 789 012',
    location: 'Eldoret',
    joinDate: '2024-01-18',
    totalSpent: 32000,
    visitCount: 1,
    status: 'active',
    lastPurchase: '2024-01-19',
  },
  {
    id: '6',
    name: 'Vikram Kumar',
    phone: '+254 717 890 123',
    location: 'Thika',
    joinDate: '2024-01-19',
    totalSpent: 3500,
    visitCount: 1,
    status: 'active',
    lastPurchase: '2024-01-18',
  },
  {
    id: '7',
    name: 'Neha Gupta',
    phone: '+254 718 901 234',
    location: 'Nairobi',
    joinDate: '2024-01-20',
    totalSpent: 8000,
    visitCount: 1,
    status: 'active',
    lastPurchase: '2024-01-17',
  },
];

export const mockRepeatCustomersData: RepeatCustomer[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    phone: '+91 98765 43210',
    location: 'Mumbai',
    joinDate: '2023-01-10',
    totalSpent: 45000,
    visitCount: 12,
    status: 'active',
    lastPurchase: '2024-01-15',
    repeatPercentage: 92,
    loyaltyTier: 'platinum',
  },
  {
    id: '6',
    name: 'Vikram Gupta',
    email: 'vikram@example.com',
    phone: '+91 43210 98765',
    location: 'Chennai',
    joinDate: '2023-09-18',
    totalSpent: 52000,
    visitCount: 15,
    status: 'active',
    lastPurchase: '2024-01-12',
    repeatPercentage: 88,
    loyaltyTier: 'platinum',
  },
  {
    id: '8',
    name: 'Arjun Singh',
    email: 'arjun@example.com',
    phone: '+91 21098 76543',
    location: 'Jaipur',
    joinDate: '2023-12-01',
    totalSpent: 38000,
    visitCount: 10,
    status: 'active',
    lastPurchase: '2024-01-11',
    repeatPercentage: 85,
    loyaltyTier: 'gold',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 87654 32109',
    location: 'Delhi',
    joinDate: '2023-03-15',
    totalSpent: 32000,
    visitCount: 8,
    status: 'active',
    lastPurchase: '2024-01-14',
    repeatPercentage: 78,
    loyaltyTier: 'gold',
  },
];

export const mockPromotionsData: Promotion[] = [
  {
    id: '1',
    title: 'New Year Mega Sale',
    discountType: 'percentage',
    discountValue: 20,
    code: 'NEWYEAR20',
    startDate: '2024-01-01',
    endDate: '2024-01-31',
    status: 'active',
    usageCount: 145,
    targetAmount: 500000,
  },
  {
    id: '2',
    title: 'First Time Customer Offer',
    discountType: 'fixed',
    discountValue: 500,
    code: 'WELCOME500',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    status: 'active',
    usageCount: 89,
    targetAmount: 200000,
  },
  {
    id: '3',
    title: 'Winter Clearance',
    discountType: 'percentage',
    discountValue: 35,
    code: 'WINTER35',
    startDate: '2023-12-15',
    endDate: '2024-01-15',
    status: 'ended',
    usageCount: 234,
    targetAmount: 800000,
  },
  {
    id: '4',
    title: 'Loyalty Rewards',
    discountType: 'percentage',
    discountValue: 15,
    code: 'LOYALTY15',
    startDate: '2024-02-01',
    endDate: '2024-02-28',
    status: 'scheduled',
    usageCount: 0,
    targetAmount: 300000,
  },
];

export const mockWhatsAppAutomations: WhatsAppAutomation[] = [
  {
    id: '1',
    name: 'Welcome Message',
    trigger: 'New Customer',
    template: 'Welcome to our store! We\'re excited to serve you.',
    status: 'active',
    createdDate: '2024-01-01',
    messagesSent: 234,
  },
  {
    id: '2',
    name: 'Order Confirmation',
    trigger: 'New Order',
    template: 'Thank you for your order! Your order #{{orderId}} has been confirmed.',
    status: 'active',
    createdDate: '2024-01-05',
    messagesSent: 89,
  },
  {
    id: '3',
    name: 'Shipping Update',
    trigger: 'Order Shipped',
    template: 'Your order is on the way! Tracking: {{trackingId}}',
    status: 'active',
    createdDate: '2024-01-10',
    messagesSent: 67,
  },
  {
    id: '4',
    name: 'Promotion Alert',
    trigger: 'Manual Trigger',
    template: 'Limited time offer! Get 20% off on all products. Use code NEWYEAR20',
    status: 'inactive',
    createdDate: '2024-01-12',
    messagesSent: 450,
  },
  {
    id: '5',
    name: 'Follow-up Reminder',
    trigger: 'No Purchase (30 Days)',
    template: 'We miss you! Come back and shop with us. Exclusive offer inside!',
    status: 'active',
    createdDate: '2024-01-08',
    messagesSent: 156,
  },
];

export const mockRemindersData: Reminder[] = [
  {
    id: '1',
    title: 'Follow-up with Rajesh',
    description: 'Check on satisfaction with previous purchase',
    type: 'followup',
    customer: 'Rajesh Kumar',
    dueDate: '2024-01-18',
    status: 'pending',
    createdDate: '2024-01-15',
  },
  {
    id: '2',
    title: 'Priya Birthday Offer',
    description: 'Send birthday discount offer',
    type: 'birthday',
    customer: 'Priya Sharma',
    dueDate: '2024-01-20',
    status: 'pending',
    createdDate: '2024-01-15',
  },
  {
    id: '3',
    title: 'Amit Product Restock',
    description: 'Remind about new stock arrival',
    type: 'custom',
    customer: 'Amit Patel',
    dueDate: '2024-01-17',
    status: 'pending',
    createdDate: '2024-01-15',
  },
  {
    id: '4',
    title: 'Deepak Anniversary Special',
    description: 'Customer anniversary - send special offer',
    type: 'anniversary',
    customer: 'Deepak Verma',
    dueDate: '2024-01-22',
    status: 'pending',
    createdDate: '2024-01-15',
  },
  {
    id: '5',
    title: 'Sneha Payment Follow-up',
    description: 'Follow up on pending payment',
    type: 'followup',
    customer: 'Sneha Singh',
    dueDate: '2024-01-16',
    status: 'completed',
    createdDate: '2024-01-10',
  },
];

export const mockUsersData: User[] = [
  {
    id: '1',
    name: 'Raj Patel',
    email: 'raj@business.com',
    phone: '+91 98765 43210',
    role: 'admin',
    status: 'active',
    permissions: ['view_all', 'edit_all', 'delete_users', 'manage_dashboard'],
    joinDate: '2023-01-01',
    lastLogin: '2024-01-15',
  },
  {
    id: '2',
    name: 'Priya Verma',
    email: 'priya.verma@business.com',
    phone: '+91 87654 32109',
    role: 'manager',
    status: 'active',
    permissions: ['view_all', 'edit_sales', 'edit_customers', 'view_reports'],
    joinDate: '2023-05-10',
    lastLogin: '2024-01-14',
  },
  {
    id: '3',
    name: 'Amit Singh',
    email: 'amit.singh@business.com',
    phone: '+91 76543 21098',
    role: 'manager',
    status: 'active',
    permissions: ['view_sales', 'view_customers', 'edit_expenses', 'manage_promotions'],
    joinDate: '2023-06-15',
    lastLogin: '2024-01-13',
  },
  {
    id: '4',
    name: 'Sneha Reddy',
    email: 'sneha.r@business.com',
    phone: '+91 65432 10987',
    role: 'staff',
    status: 'active',
    permissions: ['view_sales', 'view_customers', 'add_reminders'],
    joinDate: '2023-08-20',
    lastLogin: '2024-01-12',
  },
  {
    id: '5',
    name: 'Vikram Kumar',
    email: 'vikram.k@business.com',
    phone: '+91 54321 09876',
    role: 'staff',
    status: 'active',
    permissions: ['view_sales', 'edit_marketing', 'manage_whatsapp'],
    joinDate: '2023-09-05',
    lastLogin: '2024-01-11',
  },
  {
    id: '6',
    name: 'Neha Gupta',
    email: 'neha.g@business.com',
    phone: '+91 43210 98765',
    role: 'staff',
    status: 'inactive',
    permissions: ['view_sales', 'view_customers'],
    joinDate: '2023-10-12',
    lastLogin: '2023-12-28',
  },
];

export const mockSalesChartData = [
  { date: 'Jan 1', sales: 24000, expenses: 14000 },
  { date: 'Jan 2', sales: 28000, expenses: 15000 },
  { date: 'Jan 3', sales: 22000, expenses: 13000 },
  { date: 'Jan 4', sales: 32000, expenses: 16000 },
  { date: 'Jan 5', sales: 25000, expenses: 14000 },
  { date: 'Jan 6', sales: 35000, expenses: 18000 },
  { date: 'Jan 7', sales: 30000, expenses: 15000 },
  { date: 'Jan 8', sales: 28000, expenses: 15000 },
  { date: 'Jan 9', sales: 26000, expenses: 14000 },
  { date: 'Jan 10', sales: 38000, expenses: 17000 },
  { date: 'Jan 11', sales: 32000, expenses: 16000 },
  { date: 'Jan 12', sales: 40000, expenses: 19000 },
  { date: 'Jan 13', sales: 28000, expenses: 15000 },
  { date: 'Jan 14', sales: 35000, expenses: 17000 },
  { date: 'Jan 15', sales: 42000, expenses: 20000 },
];

export const mockExpenseByCategoryData = [
  { name: 'Salaries', value: 25000, fill: '#3b82f6' },
  { name: 'Rent', value: 15000, fill: '#10b981' },
  { name: 'Inventory', value: 8000, fill: '#f59e0b' },
  { name: 'Marketing', value: 3000, fill: '#8b5cf6' },
  { name: 'Technology', value: 5000, fill: '#ec4899' },
  { name: 'Other', value: 5700, fill: '#6b7280' },
];

export const mockSalesByCategoryData = [
  { name: 'Services', value: 18000, fill: '#3b82f6' },
  { name: 'Products', value: 24000, fill: '#10b981' },
];

export const mockCustomerMetrics = {
  totalCustomers: 8,
  activeCustomers: 7,
  inactiveCustomers: 1,
  repeatCustomers: 4,
  newCustomers: 2,
};

export function calculateDerivedCustomers(): Customer[] {
  const customerMap = new Map<string, {
    name: string;
    phone: string;
    totalSpent: number;
    visitCount: number;
    lastPurchase: string;
  }>();

  mockSalesData.forEach(sale => {
    const key = sale.customerPhone;
    if (customerMap.has(key)) {
      const existing = customerMap.get(key)!;
      existing.totalSpent += sale.amount;
      existing.visitCount += 1;
      if (sale.date > existing.lastPurchase) {
        existing.lastPurchase = sale.date;
      }
    } else {
      customerMap.set(key, {
        name: sale.customerName,
        phone: sale.customerPhone,
        totalSpent: sale.amount,
        visitCount: 1,
        lastPurchase: sale.date,
      });
    }
  });

  let id = 1;
  return Array.from(customerMap.values()).map(customer => ({
    id: String(id++),
    name: customer.name,
    phone: customer.phone,
    location: 'Nairobi', // Default location
    joinDate: mockSalesData.find(s => s.customerPhone === customer.phone)?.date || new Date().toISOString().split('T')[0],
    totalSpent: customer.totalSpent,
    visitCount: customer.visitCount,
    status: customer.visitCount > 1 ? 'active' : 'active',
    lastPurchase: customer.lastPurchase,
  }));
}

export function calculateDashboardStats() {
  const totalSales = mockSalesData
    .filter((s) => s.status === 'completed')
    .reduce((sum, s) => sum + s.amount, 0);
  const totalExpenses = mockExpensesData.reduce((sum, e) => sum + e.amount, 0);
  const profitMargin = ((totalSales - totalExpenses) / totalSales) * 100;
  const derivedCustomers = calculateDerivedCustomers();

  return {
    totalSales,
    totalExpenses,
    totalCustomers: derivedCustomers.length,
    repeatCustomers: derivedCustomers.filter(c => c.visitCount > 1).length,
    profitMargin: Math.round(profitMargin),
    activePromotions: mockPromotionsData.filter((p) => p.status === 'active').length,
  };
}

export const mockCompanySettings: CompanySettings = {
  companyName: 'TechFlow Solutions Pvt Ltd',
  companyEmail: 'contact@techflow.com',
  companyPhone: '+91 98765 43210',
  companyAddress: '123 Business Plaza, Tech Park',
  companyCity: 'Bangalore',
  companyState: 'Karnataka',
  companyZip: '560076',
  companyLogo: '/placeholder-logo.png',
  adminEmail: 'raj@business.com',
  adminPhone: '+91 98765 43210',
  businessType: 'Technology & Services',
  taxId: 'AAXCT1234A2Z5',
  timezone: 'IST (UTC+5:30)',
  currency: 'KSh (KES)',
};

export const mockPurchasesData: Purchase[] = [
  {
    id: '1',
    date: '2024-01-15',
    vendorName: 'Tech Supplies Co',
    category: 'Electronics',
    description: 'Laptop Computers (5 units)',
    quantity: 5,
    unitPrice: 45000,
    totalAmount: 225000,
    paymentMethod: 'Bank Transfer',
    status: 'delivered',
    deliveryDate: '2024-01-18',
  },
  {
    id: '2',
    date: '2024-01-16',
    vendorName: 'Office Depot',
    category: 'Stationery',
    description: 'Office Supplies Bundle',
    quantity: 1,
    unitPrice: 8500,
    totalAmount: 8500,
    paymentMethod: 'Credit Card',
    status: 'delivered',
    deliveryDate: '2024-01-17',
  },
  {
    id: '3',
    date: '2024-01-18',
    vendorName: 'Furniture Plus',
    category: 'Furniture',
    description: 'Office Chairs (10 units)',
    quantity: 10,
    unitPrice: 12000,
    totalAmount: 120000,
    paymentMethod: 'Bank Transfer',
    status: 'pending',
  },
  {
    id: '4',
    date: '2024-01-19',
    vendorName: 'Cloud Services Ltd',
    category: 'Software',
    description: 'Annual Software License',
    quantity: 1,
    unitPrice: 50000,
    totalAmount: 50000,
    paymentMethod: 'Credit Card',
    status: 'delivered',
    deliveryDate: '2024-01-19',
  },
  {
    id: '5',
    date: '2024-01-20',
    vendorName: 'Paper Mills Inc',
    category: 'Stationery',
    description: 'Paper & Printing Materials',
    quantity: 500,
    unitPrice: 5,
    totalAmount: 2500,
    paymentMethod: 'Debit Card',
    status: 'cancelled',
  },
  {
    id: '6',
    date: '2024-01-21',
    vendorName: 'Industrial Supply',
    category: 'Equipment',
    description: 'Backup Power System',
    quantity: 1,
    unitPrice: 85000,
    totalAmount: 85000,
    paymentMethod: 'Bank Transfer',
    status: 'pending',
  },
  {
    id: '7',
    date: '2024-01-22',
    vendorName: 'Network Solutions',
    category: 'IT Equipment',
    description: 'Networking Hardware',
    quantity: 8,
    unitPrice: 6500,
    totalAmount: 52000,
    paymentMethod: 'Bank Transfer',
    status: 'delivered',
    deliveryDate: '2024-01-24',
  },
  {
    id: '8',
    date: '2024-01-23',
    vendorName: 'Green Energy Co',
    category: 'Utilities',
    description: 'Solar Panel Installation',
    quantity: 1,
    unitPrice: 150000,
    totalAmount: 150000,
    paymentMethod: 'Bank Transfer',
    status: 'pending',
  },
];
